services:
  - type: web
    name: digital-business-card
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
    postDeployCommand: flask db upgrade
